### ISSUE TITLE
Regarding Image Segmentation

### ISSUE THREAD

**Issue by seekingdeep** [anki-xyz/GlottalMidline#1]
@anki-xyz Hi there,
recently i came across a paper that you published called 
**(Efficient Biomedical Image Segmentation on EdgeTPUs at Point of Care)**

it seems promising, and i was wondering will the code be open-sourced at Github?
perhaps releasing the code for the cpu-only part, if you can't release the tpu part.

waiting for your reply

**Comment by anki-xyz** [comment]
This is not an issue with this project; please write me an email. Closed.
